import React from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleProp, StyleSheet, Text, TextInput, TextInputProps, useWindowDimensions, View, ViewStyle } from 'react-native';
import { useApp } from '@/context/AppContext';
import { shadowFor, ThemeColors, ThemeMode } from '@/theme';
import { ItemStatus, STATUS_META } from '@/types/domain';

function useUIStyles() { const app = useApp(); return createStyles(app.themeColors, app.themeMode); }

export function Page({ children, title, subtitle, action }: React.PropsWithChildren<{ title: string; subtitle?: string; action?: React.ReactNode }>) {
  const { width } = useWindowDimensions(); const narrow = width < 480; const styles = useUIStyles();
  return <ScrollView style={styles.page} contentContainerStyle={[styles.pageContent, narrow && styles.pageContentNarrow]}><View style={[styles.titleRow, narrow && styles.titleRowNarrow]}><View style={{ flex: narrow ? undefined : 1 }}><Text style={styles.eyebrow}>SAARLY</Text><Text accessibilityRole="header" style={[styles.h1, narrow && styles.h1Narrow]}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{action ? <View style={narrow && styles.actionNarrow}>{action}</View> : null}</View>{children}</ScrollView>;
}
export function Card({ children, style }: React.PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { const styles = useUIStyles(); return <View style={[styles.card, style]}>{children}</View>; }
export function Button({ label, onPress, variant = 'primary', icon, disabled, testID }: { label: string; onPress: () => void; variant?: 'primary' | 'secondary' | 'danger' | 'ghost'; icon?: string; disabled?: boolean; testID?: string }) {
  const styles = useUIStyles();
  return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, styles[`button_${variant}`], pressed && styles.pressed, disabled && styles.disabled]}><Text style={[styles.buttonText, styles[`buttonText_${variant}`]]}>{icon ? `${icon}  ` : ''}{label}</Text></Pressable>;
}
export function Field(props: TextInputProps & { label: string }) { const app = useApp(); const styles = useUIStyles(); return <View style={{ gap: 7 }}><Text style={styles.label}>{props.label}</Text><TextInput placeholderTextColor={app.themeColors.timestamp} {...props} style={[styles.input, props.multiline && { minHeight: 90, textAlignVertical: 'top' }, props.style]} /></View>; }
export function StatusBadge({ status }: { status: ItemStatus }) { const styles = useUIStyles(); const meta = STATUS_META[status]; return <View style={[styles.badge, { backgroundColor: meta.background }]}><Text style={[styles.badgeText, { color: meta.color }]}>{meta.icon} {meta.label}</Text></View>; }
export function Avatar({ name, color, size = 38 }: { name: string; color: string; size?: number }) { return <View accessibilityLabel={name} style={{ width: size, height: size, borderRadius: size / 2, backgroundColor: color, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#fff', fontWeight: '800', fontSize: size * .38 }}>{name.slice(0, 1)}</Text></View>; }
export function Empty({ icon, title, body }: { icon: string; title: string; body: string }) { const styles = useUIStyles(); return <Card style={{ alignItems: 'center', paddingVertical: 40 }}><Text style={styles.emptyIcon}>{icon}</Text><Text style={styles.emptyTitle}>{title}</Text><Text style={[styles.subtitle, { textAlign: 'center' }]}>{body}</Text></Card>; }
export function Loading() { const app = useApp(); const styles = useUIStyles(); return <View style={styles.loading}><ActivityIndicator size="large" color={app.themeColors.primary} /><Text style={styles.subtitle}>Laadin Saarlyt…</Text></View>; }
export function Sheet({ visible, title, onClose, children }: React.PropsWithChildren<{ visible: boolean; title: string; onClose: () => void }>) { const styles = useUIStyles(); return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.overlay} onPress={onClose}><Pressable style={styles.sheet} onPress={(event) => event.stopPropagation()}><View style={styles.sheetHeader}><Text style={styles.h2}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Sulge" onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={{ gap: 16 }}>{children}</ScrollView></Pressable></Pressable></Modal>; }

function createStyles(colors: ThemeColors, mode: ThemeMode) { return StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background }, pageContent: { padding: 24, paddingBottom: 110, width: '100%', maxWidth: 1040, alignSelf: 'center', gap: 18 }, pageContentNarrow: { paddingHorizontal: 18 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 8, marginBottom: 4 }, titleRowNarrow: { flexDirection: 'column', alignItems: 'stretch', gap: 12 }, actionNarrow: { alignSelf: 'stretch' }, eyebrow: { color: colors.primary, fontSize: 12, fontWeight: '900', letterSpacing: 2 }, h1: { color: colors.ink, fontSize: 32, lineHeight: 40, fontWeight: '800' }, h1Narrow: { fontSize: 30, lineHeight: 37 }, h2: { color: colors.ink, fontSize: 21, fontWeight: '800' }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 4 },
  card: { backgroundColor: colors.surface, borderRadius: 18, borderWidth: 1, borderColor: colors.border, padding: 18, gap: 13, ...shadowFor(mode) },
  button: { minHeight: 48, paddingHorizontal: 18, paddingVertical: 12, borderRadius: 13, alignItems: 'center', justifyContent: 'center', borderWidth: 1 }, button_primary: { backgroundColor: colors.primary, borderColor: colors.primary }, button_secondary: { backgroundColor: colors.primarySoft, borderColor: colors.secondaryBorder }, button_danger: { backgroundColor: colors.dangerSoft, borderColor: colors.dangerBorder }, button_ghost: { backgroundColor: 'transparent', borderColor: colors.border }, pressed: { opacity: .72 }, disabled: { opacity: .4 }, buttonText: { fontSize: 16, fontWeight: '800' }, buttonText_primary: { color: colors.onPrimary }, buttonText_secondary: { color: colors.primaryDark }, buttonText_danger: { color: colors.danger }, buttonText_ghost: { color: colors.ink },
  label: { color: colors.ink, fontSize: 15, fontWeight: '700' }, input: { minHeight: 50, borderWidth: 1, borderColor: colors.fieldBorder, backgroundColor: colors.field, borderRadius: 12, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, color: colors.ink },
  badge: { alignSelf: 'flex-start', borderRadius: 99, paddingHorizontal: 10, paddingVertical: 6 }, badgeText: { fontSize: 13, fontWeight: '800' }, emptyIcon: { color: colors.ink, fontSize: 35 }, emptyTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', marginTop: 5 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background, gap: 12 },
  overlay: { flex: 1, backgroundColor: colors.overlay, alignItems: 'center', justifyContent: 'center', padding: 18 }, sheet: { backgroundColor: colors.background, width: '100%', maxWidth: 540, maxHeight: '88%', padding: 22, borderRadius: 22 }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 }, close: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.close, alignItems: 'center', justifyContent: 'center' }, closeText: { fontSize: 22, color: colors.ink },
}); }
