import React from 'react';
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleProp, StyleSheet, Text, TextInput, TextInputProps, useWindowDimensions, View, ViewStyle } from 'react-native';
import { useApp } from '@/context/AppContext';
import { shadowFor, ThemeColors, ThemeMode } from '@/theme';
import { ItemStatus, STATUS_META } from '@/types/domain';
import { AppIcon, AppIconName } from './AppIcon';

function useUIStyles() { const app = useApp(); return createStyles(app.themeColors, app.themeMode); }

const symbolIcons: Record<string, AppIconName> = {
  '+': 'plus', '!': 'alert', '✓': 'check', '⚓': 'ship', '□': 'archive', '☷': 'list', '○': 'floating',
  '✎': 'edit', '↗': 'external', '☎': 'phone', '↻': 'refresh', '☀': 'sun', '☾': 'moon', '×': 'close',
  '▣': 'image', '◉': 'camera', '↑': 'arrow-up', '↓': 'arrow-down', '‹': 'arrow-left', '?': 'help', '€': 'euro',
};

export function Page({ children, title, subtitle, action }: React.PropsWithChildren<{ title: string; subtitle?: string; action?: React.ReactNode }>) {
  const { width } = useWindowDimensions(); const narrow = width < 480; const styles = useUIStyles();
  return <ScrollView style={styles.page} contentContainerStyle={[styles.pageContent, narrow && styles.pageContentNarrow]}><View style={[styles.titleRow, narrow && styles.titleRowNarrow]}><View style={{ flex: narrow ? undefined : 1 }}><Text accessibilityRole="header" style={[styles.h1, narrow && styles.h1Narrow]}>{title}</Text>{subtitle ? <Text style={styles.subtitle}>{subtitle}</Text> : null}</View>{action ? <View style={narrow && styles.actionNarrow}>{action}</View> : null}</View>{children}</ScrollView>;
}
export function Card({ children, style }: React.PropsWithChildren<{ style?: StyleProp<ViewStyle> }>) { const styles = useUIStyles(); return <View style={[styles.card, style]}>{children}</View>; }
export function Button({ label, onPress, variant = 'primary', icon, disabled, testID }: { label: string; onPress: () => void; variant?: 'primary' | 'secondary' | 'danger' | 'ghost'; icon?: string; disabled?: boolean; testID?: string }) {
  const app = useApp(); const styles = useUIStyles(); const iconName = icon ? symbolIcons[icon] : undefined;
  const iconColor = variant === 'primary' ? app.themeColors.onPrimary : variant === 'danger' ? app.themeColors.danger : variant === 'secondary' ? app.themeColors.primaryDark : app.themeColors.ink;
  return <Pressable testID={testID} accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.button, styles[`button_${variant}`], pressed && styles.pressed, disabled && styles.disabled]}><View style={styles.buttonContent}>{iconName ? <AppIcon name={iconName} color={iconColor} size={19} strokeWidth={2.1} /> : icon ? <Text style={[styles.buttonIcon, styles[`buttonText_${variant}`]]}>{icon}</Text> : null}<Text style={[styles.buttonText, styles[`buttonText_${variant}`]]}>{label}</Text></View></Pressable>;
}
export function Field(props: TextInputProps & { label: string }) { const app = useApp(); const styles = useUIStyles(); return <View style={{ gap: 7 }}><Text style={styles.label}>{props.label}</Text><TextInput placeholderTextColor={app.themeColors.timestamp} {...props} style={[styles.input, props.multiline && { minHeight: 90, textAlignVertical: 'top' }, props.style]} /></View>; }
export function StatusBadge({ status }: { status: ItemStatus }) { const styles = useUIStyles(); const meta = STATUS_META[status]; return <View style={styles.badge}><View style={[styles.badgeDot, { backgroundColor: meta.color }]} /><Text style={styles.badgeText}>{meta.label}</Text></View>; }
export function Avatar({ name, color, size = 38 }: { name: string; color: string; size?: number }) { return <View accessibilityLabel={name} style={{ width: size, height: size, borderRadius: size / 2, backgroundColor: color, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: '#fff', fontWeight: '800', fontSize: size * .38 }}>{name.slice(0, 1)}</Text></View>; }
export function Empty({ icon, title, body }: { icon: string; title: string; body: string }) { const app = useApp(); const styles = useUIStyles(); const iconName = symbolIcons[icon]; return <Card style={{ alignItems: 'center', paddingVertical: 38 }}>{iconName ? <View style={styles.emptyIconWrap}><AppIcon name={iconName} color={app.themeColors.muted} size={26} strokeWidth={1.8} /></View> : <Text style={styles.emptyIcon}>{icon}</Text>}<Text style={styles.emptyTitle}>{title}</Text><Text style={[styles.subtitle, { textAlign: 'center' }]}>{body}</Text></Card>; }
export function Loading() { const app = useApp(); const styles = useUIStyles(); return <View style={styles.loading}><ActivityIndicator size="large" color={app.themeColors.primary} /><Text style={styles.subtitle}>Laadin Saarlyt…</Text></View>; }
export function Sheet({ visible, title, onClose, children }: React.PropsWithChildren<{ visible: boolean; title: string; onClose: () => void }>) { const styles = useUIStyles(); return <Modal visible={visible} transparent animationType="fade" onRequestClose={onClose}><Pressable style={styles.overlay} onPress={onClose}><Pressable style={styles.sheet} onPress={(event) => event.stopPropagation()}><View style={styles.sheetHeader}><Text style={styles.h2}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Sulge" onPress={onClose} style={styles.close}><Text style={styles.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={{ gap: 16 }}>{children}</ScrollView></Pressable></Pressable></Modal>; }

function createStyles(colors: ThemeColors, mode: ThemeMode) { return StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background }, pageContent: { padding: 26, paddingBottom: 112, width: '100%', maxWidth: 1040, alignSelf: 'center', gap: 16 }, pageContentNarrow: { paddingHorizontal: 18, paddingTop: 20 },
  titleRow: { flexDirection: 'row', alignItems: 'center', gap: 16, marginTop: 8, marginBottom: 8 }, titleRowNarrow: { flexDirection: 'column', alignItems: 'stretch', gap: 12 }, actionNarrow: { alignSelf: 'stretch' }, h1: { color: colors.ink, fontSize: 30, lineHeight: 37, fontWeight: '700', letterSpacing: -.45 }, h1Narrow: { fontSize: 28, lineHeight: 34 }, h2: { color: colors.ink, fontSize: 20, fontWeight: '700', letterSpacing: -.15 }, subtitle: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 5 },
  card: { backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: colors.border, padding: 18, gap: 13, ...shadowFor(mode) },
  button: { minHeight: 48, paddingHorizontal: 17, paddingVertical: 11, borderRadius: 10, alignItems: 'center', justifyContent: 'center', borderWidth: 1 }, button_primary: { backgroundColor: colors.primary, borderColor: colors.primary }, button_secondary: { backgroundColor: colors.surface, borderColor: colors.secondaryBorder }, button_danger: { backgroundColor: colors.dangerSoft, borderColor: colors.dangerBorder }, button_ghost: { backgroundColor: 'transparent', borderColor: colors.border }, buttonContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 }, buttonIcon: { fontSize: 17, lineHeight: 20, fontWeight: '700' }, pressed: { opacity: .82 }, disabled: { opacity: .42 }, buttonText: { fontSize: 16, lineHeight: 21, fontWeight: '700' }, buttonText_primary: { color: colors.onPrimary }, buttonText_secondary: { color: colors.primaryDark }, buttonText_danger: { color: colors.danger }, buttonText_ghost: { color: colors.ink },
  label: { color: colors.ink, fontSize: 15, fontWeight: '600', marginLeft: 1 }, input: { minHeight: 50, borderWidth: 1, borderColor: colors.fieldBorder, backgroundColor: colors.field, borderRadius: 9, paddingHorizontal: 14, paddingVertical: 12, fontSize: 16, lineHeight: 22, color: colors.ink },
  badge: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 8, paddingHorizontal: 9, paddingVertical: 5, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.subtle }, badgeDot: { width: 7, height: 7, borderRadius: 4 }, badgeText: { color: colors.ink, fontSize: 13, lineHeight: 17, fontWeight: '600' }, emptyIconWrap: { width: 46, height: 46, borderRadius: 23, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.subtle, borderWidth: 1, borderColor: colors.border }, emptyIcon: { color: colors.muted, fontSize: 28 }, emptyTitle: { color: colors.ink, fontSize: 18, fontWeight: '700', marginTop: 4 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.background, gap: 12 },
  overlay: { flex: 1, backgroundColor: colors.overlay, alignItems: 'center', justifyContent: 'center', padding: 18 }, sheet: { backgroundColor: colors.background, borderWidth: 1, borderColor: colors.border, width: '100%', maxWidth: 540, maxHeight: '88%', padding: 22, borderRadius: 18, ...shadowFor(mode) }, sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 18 }, close: { width: 42, height: 42, borderRadius: 10, backgroundColor: colors.close, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, closeText: { fontSize: 21, lineHeight: 23, color: colors.ink },
}); }
