import { useMemo, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { Alert, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { ItemCard } from '@/components/ItemCard';
import { PhotoField, SelectedPhoto } from '@/components/PhotoField';
import { ItemSortControl } from '@/components/ItemSortControl';
import { Button, Card, Empty, Field, Page, Sheet, StatusBadge } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { assignedItemsForUser, profileName } from '@/data/business';
import { ItemSortOrder, sortItems } from '@/data/itemSorting';
import { ThemeColors } from '@/theme';

export default function ListDetailScreen() {
  const { id, delivery } = useLocalSearchParams<{ id: string; delivery?: string }>(); const app = useApp();
  const styles = makeStyles(app.themeColors);
  const list = app.state.lists.find((value) => value.id === id);
  const categories = useMemo(() => app.state.categories.filter((value) => value.list_id === id).sort((a, b) => a.sort_order - b.sort_order), [app.state.categories, id]);
  const [addItemOpen, setAddItemOpen] = useState(false); const [addCategoryOpen, setAddCategoryOpen] = useState(false); const [deliveryOpen, setDeliveryOpen] = useState(delivery === '1');
  const [editListOpen, setEditListOpen] = useState(false); const [editListName, setEditListName] = useState(list?.name ?? ''); const [editListDescription, setEditListDescription] = useState(list?.description ?? '');
  const [savingList, setSavingList] = useState(false); const [listError, setListError] = useState('');
  const [categoryEdit, setCategoryEdit] = useState<string | null>(null); const [categoryName, setCategoryName] = useState('');
  const [itemName, setItemName] = useState(''); const [quantity, setQuantity] = useState('1'); const [unit, setUnit] = useState(''); const [note, setNote] = useState(''); const [categoryId, setCategoryId] = useState(categories[0]?.id ?? ''); const [assignee, setAssignee] = useState<string | undefined>();
  const [itemPhoto, setItemPhoto] = useState<SelectedPhoto | null>(null); const [savingItem, setSavingItem] = useState(false);
  const [sortOrder, setSortOrder] = useState<ItemSortOrder>('newest');
  const myDelivery = app.state.deliveries.find((value) => value.list_id === id && value.courier_id === app.currentUser?.id);
  const existingDelivery = myDelivery ?? app.state.deliveries.find((value) => value.list_id === id);
  const [ship, setShip] = useState(existingDelivery?.ship_name ?? 'Baltic Queen'); const [date, setDate] = useState(existingDelivery?.departure_date ?? new Date().toISOString().slice(0, 10)); const [time, setTime] = useState(existingDelivery?.departure_time ?? ''); const [port, setPort] = useState(existingDelivery?.port ?? 'Tallinn'); const [place, setPlace] = useState(existingDelivery?.handover_place ?? 'D-terminal'); const [deliveryNote, setDeliveryNote] = useState(existingDelivery?.note ?? '');
  if (!list) return <Page title="Nimekirja ei leitud"><Empty icon="?" title="See nimekiri puudub" body="Nimekiri võis olla eemaldatud." /></Page>;
  const allItems = app.state.items.filter((value) => value.list_id === id); const done = allItems.filter((value) => value.status === 'purchased' || value.status === 'delivered').length;
  const resetItemForm = () => { setItemName(''); setQuantity('1'); setUnit(''); setNote(''); setAssignee(undefined); setItemPhoto(null); };
  const submitItem = async () => { if (!itemName.trim() || !categoryId || savingItem) return; setSavingItem(true); const saved = await app.addItem(list.id, { name: itemName.trim(), quantity: Number(quantity) || 1, unit: unit.trim() || undefined, note: note.trim() || undefined, category_id: categoryId, assigned_to: assignee }, itemPhoto ? { uri: itemPhoto.uri, mimeType: itemPhoto.mimeType, base64: itemPhoto.base64 } : undefined); setSavingItem(false); if (!saved) return; resetItemForm(); setAddItemOpen(false); };
  const openListEdit = () => { setEditListName(list.name); setEditListDescription(list.description ?? ''); setListError(''); setEditListOpen(true); };
  const submitListEdit = async () => {
    if (!editListName.trim() || savingList) return;
    setSavingList(true); setListError('');
    try { await app.updateList(list.id, editListName, editListDescription); setEditListOpen(false); }
    catch (reason) { setListError(reason instanceof Error ? reason.message : 'Nimekirja muutmine ebaõnnestus.'); }
    finally { setSavingList(false); }
  };
  const archive = () => { const execute = () => { app.archiveList(list.id); router.replace('/(app)/lists' as never); }; if (Platform.OS === 'web') { if (window.confirm('Kas arhiveerida see nimekiri?')) execute(); } else Alert.alert('Arhiveeri nimekiri?', 'Nimekirja leiab hiljem arhiivist.', [{ text: 'Loobu', style: 'cancel' }, { text: 'Arhiveeri', onPress: execute }]); };
  const myItems = assignedItemsForUser(app.state, app.currentUser?.id).filter((item) => item.list_id === list.id);
  const canSetDelivery = myItems.length > 0;
  const allMinePurchased = myItems.some((item) => item.status === 'purchased') && myItems.every((item) => item.status === 'purchased' || item.status === 'delivered');
  const saveDelivery = (delivered = false) => { app.saveDelivery(list.id, { ship_name: ship, departure_date: date, departure_time: time.trim() || undefined, port, handover_place: place, note: deliveryNote || undefined }, delivered); setDeliveryOpen(false); };
  return <Page title={list.name} subtitle={list.description} action={<View style={styles.headerActions}>{app.isCreator ? <Button label="Muuda nimekirja" icon="✎" variant="secondary" onPress={openListEdit} /> : null}<Button label="Tagasi" icon="‹" variant="ghost" onPress={() => router.back()} /></View>}>
    <Card style={styles.deliveryCard}><View style={styles.deliveryHead}><Text style={styles.shipIcon}>⚓</Text><View style={{ flex: 1 }}><Text style={styles.deliveryTitle}>Laev ja üleandmine</Text><Text style={styles.muted}>{existingDelivery ? `${profileName(app.state, existingDelivery.courier_id)} · ${existingDelivery.ship_name} · ${existingDelivery.departure_date.split('-').reverse().join('.')}${existingDelivery.departure_time ? ` kell ${existingDelivery.departure_time}` : ''}` : canSetDelivery ? 'Palun määra, mis laeva peale kauba panid.' : app.isCreator ? 'Laevainfo ilmub siia, kui oled selle määranud.' : 'Laeva saad määrata, kui sulle on sellest nimekirjast toode määratud.'}</Text></View>{existingDelivery?.status === 'delivered' ? <StatusBadge status="delivered" /> : null}</View>{existingDelivery ? <Text style={styles.deliveryPlace}>{existingDelivery.port} · üleandmine: {existingDelivery.handover_place}{existingDelivery.note ? ` · ${existingDelivery.note}` : ''}</Text> : null}{canSetDelivery ? <><Button label={myDelivery ? 'Muuda laevainfot' : 'Määra laev'} variant="secondary" onPress={() => setDeliveryOpen(true)} />{allMinePurchased && myDelivery && myDelivery.status !== 'delivered' ? <Button label="Laevale viidud" icon="⚓" onPress={() => saveDelivery(true)} /> : null}</> : null}</Card>
    <Card style={styles.summary}><View><Text style={styles.summaryValue}>{done}/{allItems.length}</Text><Text style={styles.summaryLabel}>ostetud või viidud</Text></View><View style={styles.divider} /><View><Text style={styles.summaryValue}>{allItems.filter((value) => !value.assigned_to && value.status === 'unassigned').length}</Text><Text style={styles.summaryLabel}>jooksvas listis</Text></View></Card>
    {app.isCreator ? <View style={styles.toolbar}><Button label="Lisa toode" icon="+" onPress={() => { setCategoryId(categories[0]?.id ?? ''); setAddItemOpen(true); }} /><Button label="Lisa kategooria" icon="+" variant="secondary" onPress={() => setAddCategoryOpen(true)} /></View> : null}
    {allItems.length ? <ItemSortControl value={sortOrder} onChange={setSortOrder} /> : null}
    {categories.map((category) => {
      const items = sortItems(allItems.filter((value) => value.category_id === category.id), sortOrder);
      return <View key={category.id} style={{ gap: 10 }}><View style={styles.categoryHead}><Pressable style={styles.categoryToggle} onPress={() => app.toggleCategory(category.id)}><Text style={styles.categoryArrow}>{category.collapsed ? '›' : '⌄'}</Text><Text style={styles.categoryTitle}>{category.name}</Text><Text style={styles.categoryCount}>{items.length}</Text></Pressable>{app.isCreator ? <Button label="Muuda" variant="ghost" onPress={() => { setCategoryEdit(category.id); setCategoryName(category.name); }} /> : null}</View>{!category.collapsed ? items.length ? <View style={styles.itemsGrid}>{items.map((item) => <View key={item.id} style={styles.itemWrap}><ItemCard item={item} compact /></View>)}</View> : <Card><Text style={styles.muted}>Selles kategoorias pole veel tooteid.</Text></Card> : null}</View>;
    })}
    {!categories.length ? <Empty icon="☷" title="Kategooriaid pole" body="Alusta kategooria lisamisest." /> : null}
    {app.isCreator && !list.archived_at ? <Button label="Arhiveeri lõpetatud nimekiri" variant="ghost" icon="□" onPress={archive} /> : null}

    <Sheet visible={editListOpen} title="Muuda nimekirja" onClose={() => { if (!savingList) setEditListOpen(false); }}><Field label="Nimekirja nimi" value={editListName} onChangeText={setEditListName} autoFocus /><Field label="Kirjeldus (valikuline)" value={editListDescription} onChangeText={setEditListDescription} placeholder="Lisa soovi korral kirjeldus" multiline />{listError ? <Text accessibilityRole="alert" style={{ color: app.themeColors.danger, fontSize: 16 }}>{listError}</Text> : null}<Button label={savingList ? 'Salvestan…' : 'Salvesta muudatused'} onPress={() => void submitListEdit()} disabled={!editListName.trim() || savingList} /></Sheet>
    <Sheet visible={addItemOpen} title="Lisa toode" onClose={() => { if (!savingItem) { setAddItemOpen(false); resetItemForm(); } }}><Field label="Nimetus" value={itemName} onChangeText={setItemName} placeholder="Näiteks kohv" autoFocus /><View style={styles.row}><View style={{ flex: 1 }}><Field label="Kogus" value={quantity} onChangeText={setQuantity} keyboardType="numeric" /></View><View style={{ flex: 2 }}><Field label="Ühik või pakend" value={unit} onChangeText={setUnit} placeholder="tk, 1 l, pakk" /></View></View><Field label="Märkus" value={note} onChangeText={setNote} placeholder="Valikuline täpsustus" multiline /><PhotoField value={itemPhoto} onChange={setItemPhoto} /><Choice label="Kategooria" values={categories.map((value) => ({ id: value.id, label: value.name }))} selected={categoryId} onSelect={setCategoryId} /><Choice label="Määra kasutajale või jäta jooksvasse listi" values={[{ id: '', label: 'Jooksev list' }, ...app.state.profiles.filter((profile) => app.state.groupMembers.some((member) => member.profile_id === profile.id)).map((value) => ({ id: value.id, label: value.display_name }))]} selected={assignee ?? ''} onSelect={(value) => setAssignee(value || undefined)} /><Button label={savingItem ? 'Lisan toodet…' : 'Lisa nimekirja'} onPress={() => void submitItem()} disabled={!itemName.trim() || !categoryId || savingItem} /></Sheet>
    <Sheet visible={addCategoryOpen} title="Uus kategooria" onClose={() => setAddCategoryOpen(false)}><CategoryForm onSave={(name) => { app.addCategory(list.id, name); setAddCategoryOpen(false); }} /></Sheet>
    <Sheet visible={Boolean(categoryEdit)} title="Muuda kategooriat" onClose={() => setCategoryEdit(null)}><Field label="Kategooria nimi" value={categoryName} onChangeText={setCategoryName} autoFocus /><Button label="Salvesta nimi" onPress={() => { if (categoryEdit && categoryName.trim()) app.renameCategory(categoryEdit, categoryName.trim()); setCategoryEdit(null); }} /><View style={styles.row}><View style={{ flex: 1 }}><Button label="Liiguta üles" icon="↑" variant="secondary" onPress={() => categoryEdit && app.reorderCategory(categoryEdit, -1)} /></View><View style={{ flex: 1 }}><Button label="Liiguta alla" icon="↓" variant="secondary" onPress={() => categoryEdit && app.reorderCategory(categoryEdit, 1)} /></View></View></Sheet>
    <Sheet visible={deliveryOpen} title="Laev ja üleandmine" onClose={() => setDeliveryOpen(false)}><Choice label="Varem kasutatud laevad" values={[...new Set(['Baltic Queen', ...app.state.deliveries.map((value) => value.ship_name)])].map((value) => ({ id: value, label: value }))} selected={ship} onSelect={setShip} /><Field label="Laeva nimi" value={ship} onChangeText={setShip} /><Field label="Väljumise kuupäev" value={date} onChangeText={setDate} placeholder="AAAA-KK-PP" /><Field label="Laeva väljumise kellaaeg (valikuline)" value={time} onChangeText={setTime} placeholder="Näiteks 18:00" /><Choice label="Varem kasutatud sadamad" values={[...new Set(['Tallinn', ...app.state.deliveries.map((value) => value.port)])].map((value) => ({ id: value, label: value }))} selected={port} onSelect={setPort} /><Field label="Sadam või terminal" value={port} onChangeText={setPort} /><Field label="Üleandmise koht" value={place} onChangeText={setPlace} /><Field label="Täiendav märkus" value={deliveryNote} onChangeText={setDeliveryNote} multiline /><Button label="Salvesta laevainfo" onPress={() => saveDelivery(false)} /></Sheet>
  </Page>;
}

function Choice({ label, values, selected, onSelect }: { label: string; values: { id: string; label: string }[]; selected: string; onSelect: (id: string) => void }) { const app = useApp(); const styles = makeStyles(app.themeColors); return <View style={{ gap: 8 }}><Text style={styles.choiceLabel}>{label}</Text><View style={styles.chips}>{values.map((value) => <Pressable key={value.id} onPress={() => onSelect(value.id)} style={[styles.chip, value.id === selected && styles.chipActive]}><Text style={[styles.chipText, value.id === selected && styles.chipTextActive]}>{value.label}</Text></Pressable>)}</View></View>; }
function CategoryForm({ onSave }: { onSave: (name: string) => void }) { const [name, setName] = useState(''); return <><Field label="Kategooria nimi" value={name} onChangeText={setName} placeholder="Näiteks Majapidamine" autoFocus /><Button label="Lisa kategooria" onPress={() => name.trim() && onSave(name.trim())} disabled={!name.trim()} /></>; }

const makeStyles = (colors: ThemeColors) => StyleSheet.create({ headerActions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, summary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' }, summaryValue: { color: colors.primaryDark, fontSize: 24, fontWeight: '900', textAlign: 'center' }, summaryLabel: { color: colors.muted, fontSize: 14 }, divider: { width: 1, height: 45, backgroundColor: colors.border }, toolbar: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, categoryHead: { flexDirection: 'row', alignItems: 'center', gap: 8 }, categoryToggle: { flex: 1, flexDirection: 'row', alignItems: 'center', minHeight: 48, gap: 8 }, categoryArrow: { color: colors.primary, fontSize: 25, width: 20 }, categoryTitle: { color: colors.ink, fontSize: 21, fontWeight: '900' }, categoryCount: { backgroundColor: colors.subtle, borderRadius: 99, paddingHorizontal: 9, paddingVertical: 4, fontWeight: '800', color: colors.muted }, itemsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 }, itemWrap: { minWidth: 270, flexBasis: 310, flexGrow: 1 }, muted: { color: colors.muted, fontSize: 16, lineHeight: 23 }, deliveryCard: { borderColor: colors.accentBorder, backgroundColor: colors.accentSoft }, deliveryHead: { flexDirection: 'row', alignItems: 'center', gap: 12, flexWrap: 'wrap' }, shipIcon: { fontSize: 27 }, deliveryTitle: { color: colors.ink, fontWeight: '900', fontSize: 19 }, deliveryPlace: { color: colors.accentText, fontWeight: '700', fontSize: 15 }, row: { flexDirection: 'row', gap: 10 }, choiceLabel: { color: colors.ink, fontSize: 15, fontWeight: '700' }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, chip: { borderWidth: 1, borderColor: colors.fieldBorder, backgroundColor: colors.field, borderRadius: 99, paddingHorizontal: 12, paddingVertical: 9 }, chipActive: { backgroundColor: colors.primary, borderColor: colors.primary }, chipText: { color: colors.ink, fontWeight: '700' }, chipTextActive: { color: colors.onPrimary } });
